### ISSUE TITLE
Weather Example fails with `Uncaught TypeError: Cannot read property 'AppEvents' of undefined`

### ISSUE THREAD

**Issue by gfrivolt** [wit-ai/witty-fiddle#43]
This happens when I enter something to "Chat with your bot here..." line. I tried it on the weather example at https://wit-ai.github.io/witty-fiddle/?id=5a387f6ccb4be4a1f77f2113747a558a. This link is on the `README` page.

```
Uncaught TypeError: Cannot read property 'AppEvents' of undefined
    at t.n._sendText (https://wit-ai.github.io/witty-fiddle/static/js/main.06263af8.js:25:3466)
    at n._onInputKeyDown (https://wit-ai.github.io/witty-fiddle/static/js/main.06263af8.js:25:3184)
    at Object.r (https://wit-ai.github.io/witty-fiddle/static/js/main.06263af8.js:3:12303)
    at a (https://wit-ai.github.io/witty-fiddle/static/js/main.06263af8.js:3:4290)
    at Object.s [as executeDispatchesInOrder] (https://wit-ai.github.io/witty-fiddle/static/js/main.06263af8.js:3:4505)
    at f (https://wit-ai.github.io/witty-fiddle/static/js/main.06263af8.js:1:29837)
    at p (https://wit-ai.github.io/witty-fiddle/static/js/main.06263af8.js:1:29963)
    at Array.forEach (native)
    at n (https://wit-ai.github.io/witty-fiddle/static/js/main.06263af8.js:10:13952)
    at Object.processEventQueue (https://wit-ai.github.io/witty-fiddle/static/js/main.06263af8.js:1:30970)
```

**Comment by stopachka** [comment]
Looks like window.FB is undefined -- we are looking into it now! 

https://github.com/wit-ai/witty-fiddle/issues/42
